### PR TITLE
Use zxcvbn to provide entropy-based evaluation and feedback

### PR DESCRIPTION
**Pull request by JacksonKearl**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
I thought about using zxcvbn, but was too lazy. Questions about this PR:

* Why did you remove the GIF from the README?
* Can you update your README changes so it still gives good advice on how to verify password strength? I hope people don't *actually* use this library, so we still need to tell them.

**Comment by JacksonKearl** [comment]
The old GIF had errors that were inherently nonsense given the new entropy standards. If you share the frontend you used to make it, I could make a new gif with the new errors

**Comment by SirCmpwn** [comment]
I did not keep it around. It was just a Flask app I whipped up in 5 minutes with tw bootstrap and a simple form. Regardless, I think the old GIF has more of an impact - the desired thought process is "okay, seen that before. Seen that before. Hey, what?"

**Comment by SirCmpwn** [comment]
I don't like the changes you made to the README at all. You're coming at this from a place that's critical to the GIF, which is understandable, but you don't need to be so agressive about it. Remember the first purpose of this project is to educate people about password reuse, not to be a good example of how to validate passwords (in fact, it's meant to be an awful and unethical example of how to validate passwords).

**Comment by JacksonKearl** [comment]
Understandable... this PR is turning out to be more work than I anticipated ;)

I didn't intend for the README to be aggressive, but I see how it could be interpreted as such. I'll figure something out.

**Comment by SirCmpwn** [comment]
I just wouldn't change the readme at all.

**Pull request closed without merging**
